'use strict';

/**
 * Installer Service
 *
 * Generates the PowerShell monitor script (.ps1) and the Windows batch
 * installer (.bat) that agents download from the dashboard.
 *
 * CHANGE vs. original server.js:
 *   - Both functions now accept a `monitorToken` parameter.
 *   - The generated PS1 sends an `X-Monitor-Token` header alongside
 *     `X-Webhook-Secret` in all Invoke-RestMethod calls.
 *   - The generated BAT passes the monitor token through to the
 *     download URL and webhook self-test.
 */

/**
 * Derive the base URL that monitors should use to reach the server.
 * Prefers the MONITOR_URL environment variable; falls back to request origin.
 *
 * @param {import('express').Request} req
 * @param {string|null} envMonitorUrl  Value of process.env.MONITOR_URL (may be null)
 * @returns {string}
 */
function getMonitorBaseUrl(req, envMonitorUrl) {
  if (envMonitorUrl) return envMonitorUrl;
  return `${req.protocol}://${req.get('host')}`;
}

/**
 * Generate the PowerShell call-monitor script.
 *
 * This is the script that runs in the background on the agent's Windows PC,
 * watches for Phone Link / WhatsApp call notifications via WinRT, and POSTs
 * them to the server's /incoming_call endpoint.
 *
 * @param {string} baseUrl       Server URL (e.g. https://calls.example.com)
 * @param {string} secret        Webhook secret (X-Webhook-Secret)
 * @param {string} agent         Agent username (e.g. "agent1")
 * @param {string} monitorToken  Per-agent monitor token (X-Monitor-Token)
 * @returns {string} Complete PS1 script content
 */
function generateMonitorScript(baseUrl, secret, agent, monitorToken) {
  // Use array join to avoid JS template literal conflicts with PowerShell backticks
  const BT = '`'; // PowerShell backtick (line continuation)
  const lines = [
    '# =========================',
    '# call_monitor.ps1',
    '# Phone Link -> CRM monitor',
    '# Agent: ' + agent,
    '# Windows PowerShell 5.1',
    '# =========================',
    '',
    'Add-Type -AssemblyName System.Runtime.WindowsRuntime',
    '',
    '# -------------------------------------------------',
    '# CONFIG (injected per-agent by server)',
    '# -------------------------------------------------',
    '$ServerUrl      = "' + baseUrl + '/incoming_call"',
    '$HeartbeatUrl   = "' + baseUrl + '/heartbeat"',
    '$LogUploadUrl   = "' + baseUrl + '/api/monitor-log"',
    '$WebhookSecret  = "' + secret + '"',
    '$MonitorToken   = "' + monitorToken + '"',
    '$Agent          = "' + agent + '"',
    '$PollMs         = 1200',
    '$CooldownSec    = 20',
    '$HeartbeatSec   = 30',
    '$LogDir         = Join-Path $env:APPDATA "ClinicaCallMonitor"',
    '$LogFile        = Join-Path $LogDir "call_monitor.log"',
    '$CrashLog       = Join-Path $LogDir "crash.log"',
    '$DebugMode      = $true',
    '',
    '# -------------------------------------------------',
    '# SETUP',
    '# -------------------------------------------------',
    'if (-not (Test-Path $LogDir)) {',
    '    New-Item -ItemType Directory -Path $LogDir -Force | Out-Null',
    '}',
    '',
    '# Trim log if > 1MB',
    'if (Test-Path $LogFile) {',
    '    try {',
    '        if ((Get-Item $LogFile).Length -gt 1MB) {',
    '            Get-Content $LogFile -Tail 200 | Set-Content "$LogFile.tmp"',
    '            Move-Item "$LogFile.tmp" $LogFile -Force',
    '        }',
    '    } catch {}',
    '}',
    '',
    'function Write-Log {',
    '    param(',
    '        [string]$Level,',
    '        [string]$Message',
    '    )',
    '    $line = "[{0}] [{1}] {2}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Level.ToUpper(), $Message',
    '    try { Add-Content -Path $LogFile -Value $line -ErrorAction SilentlyContinue } catch {}',
    '    if ($DebugMode) { Write-Host $line }',
    '}',
    '',
    'function Normalize-Phone {',
    '    param([string]$Raw)',
    '    if ([string]::IsNullOrWhiteSpace($Raw)) { return $null }',
    '    $p = $Raw.Trim()',
    "    if ($p -match '^00\\d+') { $p = '+' + $p.Substring(2) }",
    "    $p = $p -replace '(?!^\\+)[^\\d]', ''",
    "    $p = $p -replace '[^\\d+]', ''",
    "    if ($p.StartsWith('+')) {",
    "        $p = '+' + (($p.Substring(1)) -replace '\\+', '')",
    '    } else {',
    "        $p = $p -replace '\\+', ''",
    '    }',
    '    if ($p.Length -lt 7) { return $null }',
    '    return $p',
    '}',
    '',
    'function Get-PhoneFromText {',
    '    param([string]$Text)',
    '    if ([string]::IsNullOrWhiteSpace($Text)) { return $null }',
    "    $m = [regex]::Match($Text, '\\+?\\d[\\d\\-\\s\\(\\)]{6,}\\d')",
    '    if ($m.Success) { return Normalize-Phone $m.Value }',
    '    return $null',
    '}',
    '',
    'function Build-Headers {',
    '    $h = @{}',
    '    if (-not [string]::IsNullOrWhiteSpace($WebhookSecret)) {',
    '        $h["X-Webhook-Secret"] = $WebhookSecret',
    '    }',
    '    if (-not [string]::IsNullOrWhiteSpace($MonitorToken)) {',
    '        $h["X-Monitor-Token"] = $MonitorToken',
    '    }',
    '    return $h',
    '}',
    '',
    'function Send-Heartbeat {',
    '    $headers = Build-Headers',
    '    try {',
    '        Invoke-RestMethod -Method POST -Uri $HeartbeatUrl ' + BT,
    '            -Body "Agent=$([uri]::EscapeDataString($Agent))" ' + BT,
    '            -ContentType "application/x-www-form-urlencoded" ' + BT,
    '            -Headers $headers -TimeoutSec 10 | Out-Null',
    '        return $true',
    '    } catch {',
    '        Write-Log "WARN" "Heartbeat failed: $($_.Exception.Message)"',
    '        return $false',
    '    }',
    '}',
    '',
    'function Send-LogUpload {',
    '    $headers = Build-Headers',
    '    try {',
    '        $tail = ""',
    '        if (Test-Path $LogFile) { $tail = (Get-Content $LogFile -Tail 50) -join [char]10 }',
    '        Invoke-RestMethod -Method POST -Uri $LogUploadUrl ' + BT,
    '            -Body "Agent=$([uri]::EscapeDataString($Agent))&Log=$([uri]::EscapeDataString($tail))" ' + BT,
    '            -ContentType "application/x-www-form-urlencoded" ' + BT,
    '            -Headers $headers -TimeoutSec 5 | Out-Null',
    '    } catch {}',
    '}',
    '',
    '# -------------------------------------------------',
    '# WINRT ASYNC HELPER',
    '# -------------------------------------------------',
    '$asTaskGeneric = (',
    '    [System.WindowsRuntimeSystemExtensions].GetMethods() |',
    '    Where-Object {',
    "        $_.Name -eq 'AsTask' -and",
    '        $_.GetParameters().Count -eq 1 -and',
    "        $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation" + BT + "1'",
    '    }',
    ')[0]',
    '',
    'function Await-WinRT {',
    '    param(',
    '        [Parameter(Mandatory = $true)] $WinRtTask,',
    '        [Parameter(Mandatory = $true)] $ResultType',
    '    )',
    '    $asTask = $asTaskGeneric.MakeGenericMethod($ResultType)',
    '    $netTask = $asTask.Invoke($null, @($WinRtTask))',
    '    $netTask.Wait(-1) | Out-Null',
    '    return $netTask.Result',
    '}',
    '',
    '# -------------------------------------------------',
    '# MAIN MONITOR FUNCTION (restartable)',
    '# -------------------------------------------------',
    'function Start-Monitor {',
    '    try {',
    '        [Windows.UI.Notifications.Management.UserNotificationListener, Windows.UI.Notifications, ContentType=WindowsRuntime] | Out-Null',
    '        [Windows.UI.Notifications.NotificationKinds, Windows.UI.Notifications, ContentType=WindowsRuntime] | Out-Null',
    '        [Windows.UI.Notifications.KnownNotificationBindings, Windows.UI.Notifications, ContentType=WindowsRuntime] | Out-Null',
    '        [Windows.UI.Notifications.UserNotification, Windows.UI.Notifications, ContentType=WindowsRuntime] | Out-Null',
    '        Write-Log "INFO" "WinRT APIs loaded"',
    '    } catch {',
    '        Write-Log "ERROR" "Cannot load WinRT APIs: $_"',
    '        Add-Content -Path $CrashLog -Value "[$(Get-Date)] WinRT load failed: $_" -ErrorAction SilentlyContinue',
    '        return $false',
    '    }',
    '',
    '    $listener = [Windows.UI.Notifications.Management.UserNotificationListener]::Current',
    '    $access = $listener.GetAccessStatus()',
    '',
    '    Write-Log "INFO" "=================================================="',
    '    Write-Log "INFO" "Starting Phone Link call monitor"',
    '    Write-Log "INFO" "Agent: $Agent"',
    '    Write-Log "INFO" "Server URL: $ServerUrl"',
    '    Write-Log "INFO" "Access status: $access"',
    '    Write-Log "INFO" "PS Version: $($PSVersionTable.PSVersion)"',
    '    Write-Log "INFO" "Computer: $env:COMPUTERNAME / User: $env:USERNAME"',
    '',
    '    if ($access -ne "Allowed") {',
    '        Write-Log "ERROR" "Notification access not allowed. Enable at Settings > Privacy > Notifications"',
    '        Add-Content -Path $CrashLog -Value "[$(Get-Date)] Notification access denied: $access" -ErrorAction SilentlyContinue',
    '        return $false',
    '    }',
    '',
    '    Write-Log "INFO" "Sending initial heartbeat..."',
    '    $hbOk = Send-Heartbeat',
    '    Write-Log "INFO" "Initial heartbeat: $(if ($hbOk) { \'OK\' } else { \'FAILED\' })"',
    '',
    '    $seenNotificationIds = @{}',
    '    $recentCalls         = @{}',
    '    $lastHeartbeat       = [DateTimeOffset]::Now.ToUnixTimeSeconds()',
    '    $consecutiveErrors   = 0',
    '',
    '    Write-Log "INFO" "Listening for Phone Link incoming calls..."',
    '',
    '    while ($true) {',
    '        try {',
    '            $op = $listener.GetNotificationsAsync([Windows.UI.Notifications.NotificationKinds]::Toast)',
    '            $notifs = Await-WinRT $op ([System.Collections.Generic.IReadOnlyList[Windows.UI.Notifications.UserNotification]])',
    '            $consecutiveErrors = 0',
    '',
    '            foreach ($n in $notifs) {',
    '                $nid = [string]$n.Id',
    '                if ($seenNotificationIds.ContainsKey($nid)) { continue }',
    '                $seenNotificationIds[$nid] = Get-Date',
    '',
    '                $app = ""',
    '                try { $app = $n.AppInfo.DisplayInfo.DisplayName } catch { $app = "" }',
    '',
    '                $binding = $null',
    '                try {',
    '                    $binding = $n.Notification.Visual.GetBinding([Windows.UI.Notifications.KnownNotificationBindings]::ToastGeneric)',
    '                } catch { $binding = $null }',
    '',
    '                $texts = @()',
    '                if ($binding) {',
    '                    foreach ($t in $binding.GetTextElements()) {',
    '                        if (-not [string]::IsNullOrWhiteSpace($t.Text)) {',
    '                            $texts += $t.Text.Trim()',
    '                        }',
    '                    }',
    '                }',
    '                if ($texts.Count -eq 0) { continue }',
    '',
    '                $joined = $texts -join " | "',
    '                Write-Log "DEBUG" "Notification APP=\'$app\' TEXT=\'$joined\' ID=$nid"',
    '',
    '                # ---- STRICT MATCHING: Phone Link incoming calls only ----',
    '                if ($app -ne "Phone Link") { continue }',
    "                if ($joined -notmatch 'Incoming Call') { continue }",
    '',
    '                $caller = Get-PhoneFromText $joined',
    '                if ([string]::IsNullOrWhiteSpace($caller)) {',
    '                    if ($texts.Count -gt 0 -and $texts[0].Length -gt 0) {',
    '                        $caller = "contact:" + $texts[0].Trim()',
    '                        Write-Log "WARN" "No phone number — using contact name: $caller"',
    '                    } else {',
    "                        Write-Log \"WARN\" \"Incoming Call found but no phone number parsed. TEXT='$joined'\"",
    '                        continue',
    '                    }',
    '                }',
    '',
    '                $now = Get-Date',
    '                if ($recentCalls.ContainsKey($caller) -and ($now - $recentCalls[$caller]).TotalSeconds -lt $CooldownSec) {',
    '                    Write-Log "INFO" "Duplicate call skipped. Caller=$caller"',
    '                    continue',
    '                }',
    '                $recentCalls[$caller] = $now',
    '',
    "                Write-Log \"INFO\" \"=== CALL DETECTED: Caller=$caller App='$app' Text='$joined' ID=$nid ===\"",
    '',
    '                $headers = Build-Headers',
    '                $body = @{',
    '                    From           = $caller',
    '                    Agent          = $Agent',
    '                    CallSid        = "local-$([DateTimeOffset]::Now.ToUnixTimeSeconds())"',
    '                    Source         = "PhoneLink"',
    '                    NotificationId = $nid',
    '                    Computer       = $env:COMPUTERNAME',
    '                }',
    '',
    '                for ($retry = 1; $retry -le 3; $retry++) {',
    '                    try {',
    '                        $response = Invoke-RestMethod -Method POST -Uri $ServerUrl -Headers $headers -Body $body -TimeoutSec 15',
    '                        Write-Log "INFO" "Webhook sent OK (attempt $retry). Caller=$caller Response=$($response | ConvertTo-Json -Compress -ErrorAction SilentlyContinue)"',
    '                        break',
    '                    } catch {',
    '                        Write-Log "ERROR" "Webhook FAIL (attempt $retry). Caller=$caller Error=$($_.Exception.Message)"',
    '                        if ($retry -lt 3) { Start-Sleep -Seconds 2 }',
    '                    }',
    '                }',
    '            }',
    '',
    '            if ($seenNotificationIds.Count -gt 1000) {',
    '                $cutoff = (Get-Date).AddMinutes(-30)',
    '                $newSeen = @{}',
    '                foreach ($key in $seenNotificationIds.Keys) {',
    '                    if ($seenNotificationIds[$key] -gt $cutoff) { $newSeen[$key] = $seenNotificationIds[$key] }',
    '                }',
    '                $seenNotificationIds = $newSeen',
    '                Write-Log "DEBUG" "Cleaned seen notification cache"',
    '            }',
    '',
    '            $callCutoff = (Get-Date).AddMinutes(-10)',
    '            $newRecent = @{}',
    '            foreach ($key in $recentCalls.Keys) {',
    '                if ($recentCalls[$key] -gt $callCutoff) { $newRecent[$key] = $recentCalls[$key] }',
    '            }',
    '            $recentCalls = $newRecent',
    '',
    '        } catch {',
    '            $consecutiveErrors++',
    '            Write-Log "ERROR" "Main loop error ($consecutiveErrors): $($_.Exception.Message)"',
    '            if ($consecutiveErrors -ge 10) {',
    '                Write-Log "ERROR" "Too many consecutive errors, restarting monitor..."',
    '                Add-Content -Path $CrashLog -Value "[$(Get-Date)] Restarting after $consecutiveErrors errors: $_" -ErrorAction SilentlyContinue',
    '                return $false',
    '            }',
    '        }',
    '',
    '        $nowUnix = [DateTimeOffset]::Now.ToUnixTimeSeconds()',
    '        if (($nowUnix - $lastHeartbeat) -ge $HeartbeatSec) {',
    '            $hbOk = $false',
    '            for ($hbRetry = 1; $hbRetry -le 3; $hbRetry++) {',
    '                if (Send-Heartbeat) { $lastHeartbeat = $nowUnix; $hbOk = $true; break }',
    '                if ($hbRetry -lt 3) { Start-Sleep -Seconds 2 }',
    '            }',
    '            if (-not $hbOk) { Write-Log "WARN" "All 3 heartbeat attempts failed" }',
    '            Send-LogUpload',
    '        }',
    '',
    '        Start-Sleep -Milliseconds $PollMs',
    '    }',
    '    return $true',
    '}',
    '',
    '# -------------------------------------------------',
    '# AUTO-RESTART LOOP (up to 20 attempts)',
    '# -------------------------------------------------',
    '$maxRestarts = 20',
    'for ($restart = 0; $restart -lt $maxRestarts; $restart++) {',
    '    if ($restart -gt 0) {',
    '        $waitSec = [Math]::Min(30, 5 * $restart)',
    '        Write-Log "WARN" "Restarting monitor in $waitSec seconds (attempt $($restart + 1) / $maxRestarts)..."',
    '        Send-Heartbeat | Out-Null',
    '        Start-Sleep -Seconds $waitSec',
    '    }',
    '    $result = Start-Monitor',
    '    if ($result -eq $true) { break }',
    '}',
    'Write-Log "ERROR" "Monitor exiting after $maxRestarts restart attempts. Please re-install."',
  ];
  return lines.join('\n');
}

/**
 * Generate the Windows batch installer that downloads the PS1 script,
 * sets up scheduled tasks and startup-folder persistence, and verifies
 * the installation.
 *
 * @param {string} baseUrl       Server URL
 * @param {string} secret        Webhook secret
 * @param {string} agent         Agent username
 * @param {string} monitorToken  Per-agent monitor token
 * @returns {string} Complete BAT file content (CRLF line endings)
 */
function generateInstallerBat(baseUrl, secret, agent, monitorToken) {
  // All PowerShell commands are on SINGLE lines — no ^ continuation (breaks CMD->PS handoff)
  // Scheduled task uses /RL LIMITED (no admin needed), falls through on failure
  const lines = [
    '@echo off',
    'setlocal EnableExtensions EnableDelayedExpansion',
    'title Clinicea Call Monitor Installer - ' + agent,
    '',
    'set "AGENT=' + agent + '"',
    'set "SERVER_URL=' + baseUrl + '"',
    'set "WEBHOOK_SECRET=' + secret + '"',
    'set "MONITOR_TOKEN=' + monitorToken + '"',
    '',
    'set "APP_DIR=%APPDATA%\\ClinicaCallMonitor"',
    'set "PS1_FILE=%APP_DIR%\\call_monitor.ps1"',
    'set "VBS_FILE=%APP_DIR%\\start_monitor.vbs"',
    'set "LOG_FILE=%APP_DIR%\\install_%AGENT%.log"',
    'set "TASK_NAME=Clinicea Call Monitor - %AGENT%"',
    'set "STARTUP_VBS=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\CliniceaCallMonitor_%AGENT%.vbs"',
    'set "TASK_OK=0"',
    'set "STARTUP_OK=0"',
    'set "LAUNCH_OK=0"',
    '',
    'if not exist "%APP_DIR%" mkdir "%APP_DIR%"',
    '',
    'call :log "============================================"',
    'call :log "Starting installer for %AGENT%"',
    'call :log "App dir: %APP_DIR%"',
    'call :log "Server: %SERVER_URL%"',
    'call :log "User: %USERNAME%"',
    'echo.',
    'echo === Clinicea Call Monitor Installer ===',
    'echo Agent: %AGENT%',
    'echo.',
    '',
    'REM === Step 1: Kill ALL old monitors ===',
    'echo [1/7] Stopping ALL previous monitor instances...',
    'call :log "Stopping ALL old monitor tasks/processes"',
    'schtasks /Query /TN "%TASK_NAME%" >nul 2>&1 && schtasks /End /TN "%TASK_NAME%" >nul 2>&1',
    'powershell -NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_Process | Where-Object { $_.Name -eq \'powershell.exe\' -and $_.CommandLine -like \'*call_monitor*\' } | ForEach-Object { try { Stop-Process -Id $_.ProcessId -Force; Write-Output (\'Killed PID \' + $_.ProcessId) } catch {} }" >> "%LOG_FILE%" 2>&1',
    'powershell -NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_Process | Where-Object { $_.Name -eq \'wscript.exe\' -and $_.CommandLine -like \'*CliniceaCallMonitor*\' } | ForEach-Object { try { Stop-Process -Id $_.ProcessId -Force; Write-Output (\'Killed WScript PID \' + $_.ProcessId) } catch {} }" >> "%LOG_FILE%" 2>&1',
    'echo Done.',
    '',
    'REM === Step 2: Download PS1 (via temp script to avoid CMD escaping issues) ===',
    'echo [2/7] Downloading monitor script...',
    'call :log "Downloading call_monitor.ps1"',
    'set "DL_SCRIPT=%APP_DIR%\\dl_temp.ps1"',
    '> "%DL_SCRIPT%" echo [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
    '>> "%DL_SCRIPT%" echo $url = "%SERVER_URL%/api/monitor-script?agent=%AGENT%^&secret=%WEBHOOK_SECRET%^&token=%MONITOR_TOKEN%"',
    '>> "%DL_SCRIPT%" echo $out = "%PS1_FILE%"',
    '>> "%DL_SCRIPT%" echo Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing',
    '>> "%DL_SCRIPT%" echo if (!(Test-Path $out)) { exit 11 }',
    '>> "%DL_SCRIPT%" echo $len = (Get-Item $out).Length',
    '>> "%DL_SCRIPT%" echo if ($len -lt 100) { exit 12 }',
    '>> "%DL_SCRIPT%" echo Write-Output ("Downloaded bytes=" + $len)',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%DL_SCRIPT%" >> "%LOG_FILE%" 2>&1',
    'del /Q "%DL_SCRIPT%" >nul 2>&1',
    'if not exist "%PS1_FILE%" (',
    '    echo ERROR: Failed to download monitor script.',
    '    call :log "ERROR: Monitor script missing after download"',
    '    pause',
    '    exit /b 1',
    ')',
    'for %%A in ("%PS1_FILE%") do set "PS1_SIZE=%%~zA"',
    'if "%PS1_SIZE%"=="0" (',
    '    echo ERROR: Downloaded script is empty.',
    '    pause',
    '    exit /b 1',
    ')',
    'echo Downloaded: %PS1_SIZE% bytes',
    'call :log "Downloaded script: %PS1_SIZE% bytes"',
    'set "CHK_SCRIPT=%APP_DIR%\\chk_temp.ps1"',
    '> "%CHK_SCRIPT%" echo $content = Get-Content "%PS1_FILE%" -Raw',
    '>> "%CHK_SCRIPT%" echo if ($content -match "agentName\\s*=\\s*.+") { Write-Output "PS1 agent check: OK" } else { Write-Output "PS1 agent check: MISSING" }',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%CHK_SCRIPT%" >> "%LOG_FILE%" 2>&1',
    'del /Q "%CHK_SCRIPT%" >nul 2>&1',
    '',
    'REM === Step 3: Write VBS launcher ===',
    'echo [3/7] Writing silent launcher...',
    'call :log "Writing VBS launcher"',
    '> "%VBS_FILE%" echo Set ws = CreateObject("WScript.Shell")',
    '>> "%VBS_FILE%" echo appDir = ws.ExpandEnvironmentStrings("%APPDATA%") ^& "\\ClinicaCallMonitor"',
    '>> "%VBS_FILE%" echo ws.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File """ ^& appDir ^& "\\call_monitor.ps1""", 0, False',
    'if not exist "%VBS_FILE%" (',
    '    echo ERROR: Failed to create VBS launcher.',
    '    pause',
    '    exit /b 1',
    ')',
    'echo Done.',
    '',
    'REM === Step 4: Scheduled task — try LIMITED first (no admin), then HIGHEST ===',
    'echo [4/7] Creating scheduled task...',
    'call :log "Creating scheduled task: %TASK_NAME%"',
    'schtasks /Delete /TN "%TASK_NAME%" /F >nul 2>&1',
    'schtasks /Create /TN "%TASK_NAME%" /SC ONLOGON /RL LIMITED /TR "wscript.exe \\"%VBS_FILE%\\"" /F >> "%LOG_FILE%" 2>&1',
    'if errorlevel 1 (',
    '    call :log "LIMITED task failed, trying HIGHEST"',
    '    schtasks /Create /TN "%TASK_NAME%" /SC ONLOGON /RL HIGHEST /TR "wscript.exe \\"%VBS_FILE%\\"" /F >> "%LOG_FILE%" 2>&1',
    ')',
    'if errorlevel 1 (',
    '    echo WARNING: Scheduled task failed — using startup folder only.',
    '    call :log "WARNING: Scheduled task creation failed — will rely on startup folder"',
    ') else (',
    '    set "TASK_OK=1"',
    '    call :log "Scheduled task created OK"',
    ')',
    'echo Done.',
    '',
    'REM === Step 5: Startup folder fallback (always install as backup) ===',
    'echo [5/7] Adding startup-folder fallback...',
    'call :log "Adding startup folder fallback"',
    'del /Q "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\CliniceaCallMonitor*.vbs" >nul 2>&1',
    'copy /Y "%VBS_FILE%" "%STARTUP_VBS%" >nul 2>&1',
    'if exist "%STARTUP_VBS%" (',
    '    set "STARTUP_OK=1"',
    '    call :log "Startup folder: OK"',
    ') else (',
    '    call :log "WARNING: Startup folder copy failed"',
    ')',
    'echo Done.',
    '',
    'REM === Step 6: Start monitor + verify ===',
    'echo [6/7] Starting monitor...',
    'call :log "Starting monitor immediately"',
    'start "" wscript.exe "%VBS_FILE%"',
    'echo Waiting for monitor to start...',
    'timeout /t 5 /nobreak >nul',
    'set "VFY_SCRIPT=%APP_DIR%\\vfy_temp.ps1"',
    '> "%VFY_SCRIPT%" echo $p = Get-CimInstance Win32_Process ^| Where-Object { $_.Name -eq "powershell.exe" -and $_.CommandLine -like "*call_monitor*" }',
    '>> "%VFY_SCRIPT%" echo if ($p) { Write-Output ("Monitor running: PID " + ($p ^| Select-Object -First 1).ProcessId) } else { Write-Output "WARNING: Monitor process NOT found after launch"; exit 1 }',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%VFY_SCRIPT%" >> "%LOG_FILE%" 2>&1',
    'del /Q "%VFY_SCRIPT%" >nul 2>&1',
    'if errorlevel 1 (',
    '    echo WARNING: Monitor may not have started. Check log: %LOG_FILE%',
    '    call :log "WARNING: Monitor process not detected after launch"',
    ') else (',
    '    set "LAUNCH_OK=1"',
    '    echo Monitor started successfully.',
    ')',
    '',
    'REM === Step 7: Webhook self-test ===',
    'echo [7/7] Testing webhook connection...',
    'set "WHK_SCRIPT=%APP_DIR%\\whk_temp.ps1"',
    '> "%WHK_SCRIPT%" echo [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
    '>> "%WHK_SCRIPT%" echo try {',
    '>> "%WHK_SCRIPT%" echo   $r = Invoke-RestMethod -Uri "%SERVER_URL%/heartbeat" -Method POST -Body ("Agent=" + [uri]::EscapeDataString("%AGENT%")) -ContentType "application/x-www-form-urlencoded" -Headers @{"X-Webhook-Secret"="%WEBHOOK_SECRET%";"X-Monitor-Token"="%MONITOR_TOKEN%"} -TimeoutSec 10',
    '>> "%WHK_SCRIPT%" echo   Write-Output ("Webhook test: OK — " + ($r ^| ConvertTo-Json -Compress))',
    '>> "%WHK_SCRIPT%" echo } catch {',
    '>> "%WHK_SCRIPT%" echo   Write-Output ("Webhook test: FAILED — " + $_.Exception.Message)',
    '>> "%WHK_SCRIPT%" echo   exit 1',
    '>> "%WHK_SCRIPT%" echo }',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%WHK_SCRIPT%" >> "%LOG_FILE%" 2>&1',
    'del /Q "%WHK_SCRIPT%" >nul 2>&1',
    'if errorlevel 1 (',
    '    echo WARNING: Webhook self-test FAILED. Check server connection.',
    '    call :log "WARNING: Webhook self-test failed"',
    ') else (',
    '    echo Webhook test: OK',
    '    call :log "Webhook self-test passed"',
    ')',
    '',
    'REM === Install summary ===',
    'echo.',
    'echo ============================================',
    'echo   INSTALL SUMMARY',
    'echo ============================================',
    'echo   Agent:          %AGENT%',
    'echo   Dashboard:      %SERVER_URL%',
    'echo   Install dir:    %APP_DIR%',
    'echo   Script size:    %PS1_SIZE% bytes',
    'if "%TASK_OK%"=="1" (echo   Scheduled task:  OK) else (echo   Scheduled task:  FAILED)',
    'if "%STARTUP_OK%"=="1" (echo   Startup folder:  OK) else (echo   Startup folder:  FAILED)',
    'if "%LAUNCH_OK%"=="1" (echo   Monitor running: OK) else (echo   Monitor running: FAILED)',
    'echo   Log file:       %LOG_FILE%',
    'echo ============================================',
    '',
    'call :log "=== SUMMARY: task=%TASK_OK% startup=%STARTUP_OK% launch=%LAUNCH_OK% ==="',
    '',
    'if "%TASK_OK%"=="0" if "%STARTUP_OK%"=="0" (',
    '    echo.',
    '    echo *** WARNING: No auto-start persistence installed! ***',
    '    echo *** Monitor will not survive reboot. ***',
    '    call :log "CRITICAL: No persistence method installed"',
    ')',
    '',
    'echo.',
    'pause',
    'exit /b 0',
    '',
    ':log',
    'echo [%date% %time%] %~1>> "%LOG_FILE%"',
    'goto :eof',
  ];
  return lines.join('\r\n') + '\r\n';
}

module.exports = {
  getMonitorBaseUrl,
  generateMonitorScript,
  generateInstallerBat,
};
